In [1]:
import numpy as np

In [17]:
def create_array(num_list):
  # num_list.reverse()
  return np.array([num_list[::-1 ]],dtype='float')

In [18]:
print(create_array([1,2,3,4,5,6]))

[[6. 5. 4. 3. 2. 1.]]


In [19]:
#creating a 4*3 random matrix
random_arr = np.random.rand(4,3)
print(random_arr)

[[0.10432704 0.36440581 0.37610462]
 [0.67070083 0.93011379 0.06294105]
 [0.06286891 0.92383013 0.01216073]
 [0.22556533 0.24175769 0.01519712]]


In [21]:
reshaped_arr= random_arr.reshape(2,6)
print(reshaped_arr)

[[0.10432704 0.36440581 0.37610462 0.67070083 0.93011379 0.06294105]
 [0.06286891 0.92383013 0.01216073 0.22556533 0.24175769 0.01519712]]


In [26]:
# creating two integrer matrices

int_arr1=np.random.randint(1,10,size=(3,5))
int_arr2=np.random.randint(1,10,size=(7,5))

print("Array 1 ",int_arr1)
print("Array 2 ",int_arr2)

Array 1  [[9 2 3 7 1]
 [1 1 3 3 7]
 [1 6 6 4 7]]
Array 2  [[7 8 8 3 5]
 [8 2 7 5 7]
 [6 4 7 8 6]
 [6 7 9 5 6]
 [8 9 6 1 2]
 [4 7 7 3 9]
 [6 6 3 9 5]]


In [27]:
# concatenate arr1 and arr2
print( np.concatenate((int_arr1,int_arr2),axis=0))

[[9 2 3 7 1]
 [1 1 3 3 7]
 [1 6 6 4 7]
 [7 8 8 3 5]
 [8 2 7 5 7]
 [6 4 7 8 6]
 [6 7 9 5 6]
 [8 9 6 1 2]
 [4 7 7 3 9]
 [6 6 3 9 5]]


In [29]:
# inner and outer product

print("inner product\n",np.inner(int_arr1,int_arr2))
print("outer product\n",np.outer(int_arr1,int_arr2))

inner product
 [[129 139 145 136 117 101 143]
 [ 83  95  97  97  52 104  83]
 [150 131 146 164 116 163 131]]
outer product
 [[63 72 72 27 45 72 18 63 45 63 54 36 63 72 54 54 63 81 45 54 72 81 54  9
  18 36 63 63 27 81 54 54 27 81 45]
 [14 16 16  6 10 16  4 14 10 14 12  8 14 16 12 12 14 18 10 12 16 18 12  2
   4  8 14 14  6 18 12 12  6 18 10]
 [21 24 24  9 15 24  6 21 15 21 18 12 21 24 18 18 21 27 15 18 24 27 18  3
   6 12 21 21  9 27 18 18  9 27 15]
 [49 56 56 21 35 56 14 49 35 49 42 28 49 56 42 42 49 63 35 42 56 63 42  7
  14 28 49 49 21 63 42 42 21 63 35]
 [ 7  8  8  3  5  8  2  7  5  7  6  4  7  8  6  6  7  9  5  6  8  9  6  1
   2  4  7  7  3  9  6  6  3  9  5]
 [ 7  8  8  3  5  8  2  7  5  7  6  4  7  8  6  6  7  9  5  6  8  9  6  1
   2  4  7  7  3  9  6  6  3  9  5]
 [ 7  8  8  3  5  8  2  7  5  7  6  4  7  8  6  6  7  9  5  6  8  9  6  1
   2  4  7  7  3  9  6  6  3  9  5]
 [21 24 24  9 15 24  6 21 15 21 18 12 21 24 18 18 21 27 15 18 24 27 18  3
   6 12 21 21  9 27 18 18  9 27 

In [30]:
#reversing an array with slicing

print(np.array([1,2,3,4])[::-1])

[4 3 2 1]


In [44]:
#replace row
arr_rev =np.random.rand(5,5)
print(arr_rev)
arr_rev = np.delete(arr_rev, (2), axis=0)
arr_rev = np.insert(arr_rev, 2, np.nan, axis=0)
print("replaced row array ")
print(arr_rev)

[[0.6365121  0.98094809 0.55836937 0.27473749 0.03331816]
 [0.42457147 0.74498358 0.92390908 0.97597448 0.71964605]
 [0.12300579 0.74855425 0.38661492 0.12416528 0.90064011]
 [0.42031523 0.4795452  0.18797515 0.22869019 0.45726678]
 [0.82762348 0.10043481 0.09940821 0.81096568 0.90894093]]
replaced row array 
[[0.6365121  0.98094809 0.55836937 0.27473749 0.03331816]
 [0.42457147 0.74498358 0.92390908 0.97597448 0.71964605]
 [       nan        nan        nan        nan        nan]
 [0.42031523 0.4795452  0.18797515 0.22869019 0.45726678]
 [0.82762348 0.10043481 0.09940821 0.81096568 0.90894093]]


In [45]:
#normalization
arr_gen=np.random.randint(2,10,size=(5,5))
print(arr_gen)

[[2 8 5 2 9]
 [7 5 5 8 4]
 [9 4 7 3 2]
 [3 2 9 3 7]
 [2 2 5 6 9]]


In [51]:
arr_norm = arr_gen/(arr_gen.max()/1)
print(arr_norm)

[[0.22222222 0.88888889 0.55555556 0.22222222 1.        ]
 [0.77777778 0.55555556 0.55555556 0.88888889 0.44444444]
 [1.         0.44444444 0.77777778 0.33333333 0.22222222]
 [0.33333333 0.22222222 1.         0.33333333 0.77777778]
 [0.22222222 0.22222222 0.55555556 0.66666667 1.        ]]


In [69]:
#selecting specific numbers from arr_gen

N= list()
M=np.random.randint(2,10,size=(5,5))
(rows,columns)=M.shape
print(rows,columns)
for row in range(1,rows,2):
  # print(row)
  for column in range(0,columns,2):
    # print
    N.append(M[row,column])



5 5


In [70]:
print(N)

[7, 6, 4, 8, 8, 6]


In [73]:
N=np.array(N,ndmin=2)

In [75]:
print(N.reshape(2,3))

[[7 6 4]
 [8 8 6]]
