In [8]:
import numpy as np
vec1 = np.random.randint(0, 100, size =50)

In [9]:
vec1

array([24, 76, 39, 88, 49, 75, 79, 14, 40,  9, 69, 36,  8, 61, 35, 80, 44,
        1, 25, 87, 22, 88, 28, 89, 78, 54, 71, 85, 31, 43, 75, 92, 51, 97,
       25, 32, 11, 51, 88, 28, 28, 50, 77,  3, 42, 31, 36, 69, 91, 79])

In [10]:
from numpy.linalg import norm 
l1 = norm(vec1,1)
print(l1)

2584.0


In [11]:
l2 = norm(vec1,2)
print(l2)

414.59860105890374


In [ ]:
#2x + 5y = 20 and 3x+6y =12.

In [13]:
a = np.array([[2,5],[3,6]])

In [15]:
b= np.array([20,12])

In [16]:
sol = np.linalg.solve(a, b)

In [17]:
sol

array([-20.,  12.])

In [22]:
# import numpy as np 
  

# u = np.random.randint(0, 10, size =10)

# v = np.random.randint(0, 10, size =10)     

  
 
# v_norm = np.sqrt(sum(v**2))     
 
# u_norm = np.sqrt(sum(u**2))    
# # Apply the formula as mentioned above 
# # for projecting a vector onto the orthogonal vector n 
# # find dot product using np.dot() 
# proj_u_on_v = (np.dot(u, v)/v_norm**2)*v

In [24]:
# proj_u_on_v

array([3.15555556, 3.68148148, 4.20740741, 0.52592593, 4.20740741,
       1.05185185, 0.        , 0.        , 2.1037037 , 3.15555556])

In [23]:
# proj_v_on_u = (np.dot(u, v)/u_norm**2)*u

In [25]:
# proj_v_on_u

array([0.        , 6.35820896, 0.        , 2.11940299, 3.53233831,
       1.41293532, 4.94527363, 1.41293532, 3.53233831, 1.41293532])

In [29]:

u = np.random.randint(0, 10, size =10)

v = np.random.randint(0, 10, size =10)    

In [30]:
np.dot(u, v) / np.linalg.norm(v)

8.832373991453812

In [31]:
np.dot(u,v) / np.linalg.norm(u)

9.205497078951698